### ISSUE TITLE
Environment: Field of the Middle/ Northern Hills Art and Modeling

### ISSUE THREAD

**Issue by AvianBen** [AndrewDunne/FreeSpirit#6]
Area: Field of the Middle/ Northern Hills 

![image](https://user-images.githubusercontent.com/34182986/219985087-10fd1741-b38f-423b-aaac-83c0ff9a670e.png)

- [x] decide area to work on
- [ ] concept art for area / props
- [ ] draw over screenshot for placement stuff and landscape topology
- [ ] concept for telephone pole trees
- [ ] concept for berry bush
- [ ] concept for brambles
- [ ] concepts for little leavy plants

**Comment by AvianBen** [comment]
Initial thoughts:

Let's not start with the biggest area, but rather a smaller one as to not get overwhelmed. Let's also do something close to the school. 
![image](https://user-images.githubusercontent.com/34182986/219982091-a487e33b-7240-4065-a3b4-d7beacf51169.png)

I think I want to start with 3 main assets that will be used in an area, that will make that area be distinct from the others. Maybe one of the assets can be a unique prop, that will serve as a landmark. Probably best for the landmark to be somewhere in the middle, maybe a bit off centered for design rule of thirds purposes. The other props should serve to lead the viewer to the focal point, and then out of it into the next area. Of course, there can be diverging focal points, but I'm going to focus on one for now, and then we can diversify those once I'm a bit more comfortable with the project. 

We can also use paths to lead to focal points, but probably want to make them a bit more weathered to imply that these paths have not had major use for a long time. I think another important thing for the game will be the visual storytelling the environment does, so I should think about how the props will serve to further the narrative the environment has for us. The landmark should have some little details to make it feel like it had some significance in the world, maybe some purpose at some point in time. Smaller props should be easily adjustable for variation, unless they are going to play a specific role in a focal point. Probably want to avoid a linear feeling through the path creation using the paths and props. Maybe have little rewards in some areas that are a bit more secluded to make the player feel like there is reason to explore outside of the main path. An area near the school should have some hidden things that can be found easily, so that the player knows that there may be little environmental secrets throughout the whole game. For example, maybe a there's a couple stumps in an area, and one of these stumps is actually hollow with a little crystal sitting inside on some dead grass. Maybe an old abandoned grave lies behind one of the landmarks. Could also have special gems to shape in some locations that would only be found in that one spot. And maybe in the school there are some podiums to signify how many have been found. 

![image](https://user-images.githubusercontent.com/34182986/219984140-4bebb52b-d06c-46aa-b487-f90bf168d3fe.png)

Starting in this area! 

Field of the middle/ Northern Hills specifically. Both of these places have some pretty sparse shrubbery. 

![image](https://user-images.githubusercontent.com/34182986/219984666-d73d767a-a254-4c38-a173-f482d4f24bee.png)

![image](https://user-images.githubusercontent.com/34182986/219984673-1c989c7f-1edc-49dd-9fa4-e9848946e09d.png)

![image](https://user-images.githubusercontent.com/34182986/219984678-f36d7385-15ff-4dc1-af54-4be78c719688.png)

![image](https://user-images.githubusercontent.com/34182986/219984690-c46a8966-6780-4ad2-aacc-2efe6a716970.png)

![image](https://user-images.githubusercontent.com/34182986/219984714-f1f68714-f4ff-4a21-aa47-1f18cbd626f1.png)

I think the main props I want focus on in these areas are the berry bushes, the brambles, the kinda leafy plants

![image](https://user-images.githubusercontent.com/34182986/219984774-6d5e6724-227b-4e74-a98a-5018e4b5b4db.png)

and also maybe these telephone pole trees bc they are kinda spread around the school area as well. Don't have any landmarks in mind yet, but will update when I do. I'll also be thinking about what the gradients between the areas should look like as well. More treey near forest and more bramble leavy bushy near field of the middle.

**Comment by AndrewDunne** [comment]
archiving for now, can be re-opened later
