### ISSUE TITLE
Environment: Prop Organization

### ISSUE THREAD

**Issue by AvianBen** [AndrewDunne/FreeSpirit#8]
As I have more ideas for props I wanted to have an place to organize what props I thought could be in each area. This is a task list both to have an idea of which assets can be created, and to make sure that these props are actually placed into their respective areas. I'll try to only go in detail about props that'll be in many areas here, and leave area details to their respective issue pages in the future.

![image](https://user-images.githubusercontent.com/34182986/220066026-7f01fe01-660a-4332-a5b0-4b2ec2c8bc82.png)

Bugs:

I think these guys can be placed in most areas. Kinda wanna try my hand at making and animating some bug models bc I know they'll add life to the environment. I think that the types of creatures added to the game will only be invertebrates. No spine mfs.
- [ ] butterflies
- [ ] green beetles
- [ ] jellyfish
- [ ] Hermit Crabs
- [ ] Snails

![image](https://user-images.githubusercontent.com/34182986/220066890-8425a047-ef0e-4a71-893d-e5d572f5d59e.png)
![image](https://user-images.githubusercontent.com/34182986/220066936-1b342d17-8683-45ef-80b2-287d8aa694cc.png)
![image](https://user-images.githubusercontent.com/34182986/220066989-43c6ed07-04c0-4af7-b0a2-6dd2721a95af.png)
![image](https://user-images.githubusercontent.com/34182986/220067011-2dc6913a-9f38-4549-97cf-d2c331cde33f.png)
![image](https://user-images.githubusercontent.com/34182986/220176065-f6350753-21fc-4bb0-a4a8-cabe69cbefe7.png)
![image](https://user-images.githubusercontent.com/34182986/220176074-07fd8af5-03a4-4924-a7a2-fe71f9179386.png)
![image](https://user-images.githubusercontent.com/34182986/220176084-223d7664-d686-42d6-b579-31784b91d3e7.png)
![image](https://user-images.githubusercontent.com/34182986/220227365-8e8103a2-7879-481d-aa6d-85c3e336be94.png)
![image](https://user-images.githubusercontent.com/34182986/220227379-1ea76c91-4bb2-4920-ad11-b42170c190bf.png)
![image](https://user-images.githubusercontent.com/34182986/220227389-37d28e16-33ce-4c1d-aa7f-584d7992d772.png)

School Flatland:
- [ ] lilypads
- [ ] jellies
- [ ] telephone trees

Field of the Middle:

Northern Hills:

Northern Forest:

Cape of Emptiness:
- [ ] dead grass path

**Comment by AndrewDunne** [comment]
Archiving for now

**Comment by AndrewDunne** [comment]
Archiving for now
